### ISSUE TITLE
KataJigo may choose points less than 50% winning rate

### ISSUE THREAD

**Issue by ivysrono** [yishn/KataJigo#1]
In the battle mode, KataJigo may choose points with a winning rate of less than 50% that is not in the analysis mode.

Analysis by KataGo or KataJigo:
![图片](https://user-images.githubusercontent.com/2649544/91654165-50a4c580-ead9-11ea-8a2b-367d9082ad6a.png)

The KataJigo's choise in fact:
![图片](https://user-images.githubusercontent.com/2649544/91654172-58fd0080-ead9-11ea-83bf-2fdf8cd235ee.png)

[KataJigoTestSGF.zip](https://github.com/yishn/KataJigo/files/5146478/KataJigoTestSGF.zip)

Test in:
Windows10
nvidia 2060
KataGo 1.6.1 + KataJigo 1.0.2
g170e-b20c256x2-s5303129600-d1228401921
10s every step.

**Comment by yishn** [comment]
As you can [see in the code](https://github.com/yishn/KataJigo/blob/master/src/main.js#L108) we're always picking a variation with winrate >= 50% and scoreLead >= 0 whenever possible.
